In [7]:
import cvxpy as cp
import numpy as np

In [4]:
# Problem data.
m = 30
n = 20
np.random.seed(1)
A = np.random.randn(m, n)
b = np.random.randn(m)

# Construct the problem.
x = cp.Variable(n)
objective = cp.Minimize(cp.sum_squares(A @ x - b))
constraints = [0 <= x, x <= 1]
prob = cp.Problem(objective, constraints)

# The optimal objective value is returned by `prob.solve()`.
result = prob.solve()
# The optimal value for x is stored in `x.value`.
print(x.value)
# The optimal Lagrange multiplier for a constraint is stored in
# `constraint.dual_value`.
print(constraints[0].dual_value)

[-1.77433656e-19  2.85112420e-02  2.79388312e-19  3.30129911e-20
 -2.72474485e-19  1.49285011e-01 -9.95783234e-20  8.47436043e-20
  2.46718649e-01  5.78224144e-01 -4.05106417e-19  1.01242860e-03
 -9.40358780e-20  2.26767464e-01 -1.57681437e-19 -8.95732179e-20
 -1.21458810e-19 -1.52053051e-19  1.11261961e-19 -3.48073387e-19]
[ 2.50938945  0.          2.78354615  1.79425782 13.08579183  0.
  0.73716363  3.35344995  0.          0.          8.93825054  0.
  7.02955161  0.          4.71068649  3.18873635  2.06090107 10.08166738
  3.0481157   8.53268239]


In [18]:
A.shape

(5, 10)

In [19]:
y.shape

(5,)

In [15]:
A = np.tile(np.arange(1, 12), 5)[:-5].reshape((5, -1), order="F")
y = np.arange(1, 6)

In [55]:
# Problem 1
x1 = cp.Variable(A.shape[1])
objective = cp.Minimize(cp.norm(x1))
constraints = [cp.norm(A@x1 - y) <= 0.1]
prob = cp.Problem(objective, constraints)
res1 = prob.solve()
print(res1)
lambda_ = constraints[0].dual_value

0.29421649697090085


In [44]:
lambda_

0.07086818142507507

In [41]:
# Problem 2
x = cp.Variable(A.shape[1])
objective = cp.Minimize(cp.norm(x)**2)
constraints = [cp.norm(A@x - y) <= 0.1]
prob = cp.Problem(objective, constraints)
res = prob.solve()
print(res)


0.08656333586620392


In [42]:
# Problem 3
x = cp.Variable(A.shape[1])
objective = cp.Minimize(cp.norm(x, p=1))
constraints = [cp.norm(A@x - y) <= 0.1]
prob = cp.Problem(objective, constraints)
res = prob.solve()
print(res)

0.7876692205253679


In [56]:
# Problem 4
x = cp.Variable(A.shape[1])
objective = cp.Minimize(cp.norm(x) + lambda_ * cp.norm(A @ x - y))
prob = cp.Problem(objective)
res = prob.solve()
print(res)
print(res - lambda_ * np.linalg.norm(A @ x.value - y))
print(x.value)

0.3013032949384033
0.2942350842134638
[ 0.08865406  0.13978924 -0.03834808  0.1295622  -0.04299771  0.11933517
 -0.04291869  0.10910813 -0.03609731  0.0988811 ]


In [59]:
help(cp.norm)

Help on function norm in module cvxpy.atoms.norm:

norm(x, p: Union[int, str] = 2, axis=None, keepdims: bool = False)
    Wrapper on the different norm atoms.

    Parameters
    ----------
    x : Expression or numeric constant
        The value to take the norm of.  If `x` is 2D and `axis` is None,
        this function constructs a matrix norm.
    p : int or str, optional
        The type of norm. Valid options include any positive integer,
        'fro' (for frobenius), 'nuc' (sum of singular values), np.inf or
        'inf' (infinity norm).
    axis : The axis along which to apply the norm, if any.
    keepdims: If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one.

    Returns
    -------
    Expression
        An Expression representing the norm.



In [ ]:
cp.norm(

In [58]:
help(cp.sum_squares)

Help on function sum_squares in module cvxpy.atoms.sum_squares:

sum_squares(expr)
    The sum of the squares of the entries.

    Parameters
    ----------
    expr: Expression
        The expression to take the sum of squares of.

    Returns
    -------
    Expression
        An expression representing the sum of squares.



In [63]:
cp.outer

<function cvxpy.atoms.affine.binary_operators.outer(x, y)>

Expression(AFFINE, UNKNOWN, (5, 5))

In [67]:
# Problem 5
def g(A):
    return cp.sum(cp.norm(A, axis=0))


x = cp.Variable(5)
prob = cp.Problem(cp.Minimize(
    g(A - cp.outer(x, np.ones(10)))
))
res = prob.solve()
print(res)





63.95513871328735


In [69]:
# Problem 6
def h(A):
    return cp.sigma_max(A)


x = cp.Variable(5)
prob = cp.Problem(cp.Minimize(
    h(A - cp.outer(x, np.ones(10)))
))
res = prob.solve()
print(res)




14.392200222565956


In [ ]:
np.lines(5

In [71]:
# Problem 7
X = cp.Variable((5, 10))
objective = cp.Minimize(cp.norm(A - X, p='fro'))
constraints = [np.ones(5) @ X @ np.ones(10) == 1]
prob = cp.Problem(objective, constraints)
res = prob.solve()
print(res)


40.1636651713959


In [72]:
A.shape

(5, 10)

In [76]:
B

array([[ 1,  6, 11,  5, 10],
       [ 2,  7,  1,  6, 11],
       [ 3,  8,  2,  7,  1],
       [ 4,  9,  3,  8,  2],
       [ 5, 10,  4,  9,  3]])

In [75]:
# Problem 8
B = A[:, :5]
X = cp.Variable((5, 5))
objective = cp.Minimize(cp.norm(X - B, p='fro'))
constraints = [cp.PSD(X)]
prob = cp.Problem(objective, constraints)
res = prob.solve()
print(res)

9.428559127082282


In [68]:
cp.sigma_max

cvxpy.atoms.sigma_max.sigma_max

In [57]:
res1 - res

np.float64(-0.007086797967502445)

In [50]:
print(x.value - x1.value / np.linalg.norm(x1.value))

[ 5.66740993e-06  6.94038503e-06 -7.13548260e-06  6.68579001e-06
 -4.15124155e-06  6.43119499e-06 -5.87399147e-06  6.17659997e-06
 -1.10543780e-05  5.92200495e-06]


In [34]:
x.value

array([ 0.08864832,  0.13978233, -0.03833647,  0.12955553, -0.04299802,
        0.11932873, -0.04291792,  0.10910192, -0.03607974,  0.09887512])

In [35]:
res

0.08656333535998453

In [14]:
A

array([[ 1,  6, 11,  5, 10,  4,  9,  3,  8,  2],
       [ 2,  7,  1,  6, 11,  5, 10,  4,  9,  3],
       [ 3,  8,  2,  7,  1,  6, 11,  5, 10,  4],
       [ 4,  9,  3,  8,  2,  7,  1,  6, 11,  5],
       [ 5, 10,  4,  9,  3,  8,  2,  7,  1,  6]])

In [6]:
np.round(x.value, 3)

array([-0.   ,  0.029,  0.   ,  0.   , -0.   ,  0.149, -0.   ,  0.   ,
        0.247,  0.578, -0.   ,  0.001, -0.   ,  0.227, -0.   , -0.   ,
       -0.   , -0.   ,  0.   , -0.   ])